-- Drug Label Printing System - Supabase Schema
-- Run this SQL in your Supabase SQL Editor to set up the database.

-- Create the drugs table
CREATE TABLE IF NOT EXISTS public.drugs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  generic_name TEXT NOT NULL,       -- e.g. 'Paracetamol'
  brand_name TEXT NOT NULL DEFAULT '', -- e.g. 'Panadol'
  hk_number TEXT NOT NULL,          -- HK registration number
  ingredient TEXT NOT NULL DEFAULT '', -- active ingredient(s)
  dosage TEXT NOT NULL,              -- e.g. '500mg'
  default_usage TEXT NOT NULL DEFAULT '',       -- default usage instructions
  default_precautions TEXT NOT NULL DEFAULT '' -- default warnings
);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE public.drugs ENABLE ROW LEVEL SECURITY;

-- Allow anon access for the frontend
CREATE POLICY "Allow anon read" ON public.drugs
  FOR SELECT USING (true);

CREATE POLICY "Allow anon insert" ON public.drugs
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon update" ON public.drugs
  FOR UPDATE USING (true);

CREATE POLICY "Allow anon delete" ON public.drugs
  FOR DELETE USING (true);

-- Index for fast searches
CREATE INDEX IF NOT EXISTS idx_drugs_generic_name ON public.drugs (generic_name);
CREATE INDEX IF NOT EXISTS idx_drugs_brand_name ON public.drugs (brand_name);

-- Seed some common drugs for Hong Kong
INSERT INTO public.drugs (generic_name, brand_name, hk_number, ingredient, dosage, default_usage, default_precautions) VALUES
  ('Paracetamol', 'Panadol', 'HK-65432', 'Paracetamol 500mg', '500mg', '每日 3-4 次，每次 1-2 粒，需要時服用。24 小時內不應超過 8 粒。', '此藥引致昏睡，服藥後避免駕駛或操作機械。避免與其他含撲熱息痛之藥物同時服用。'),
  ('Paracetamol', '必理痛', 'HK-65433', 'Paracetamol 500mg', '500mg', '每日 3-4 次，每次 1-2 粒，需要時服用。', '避免與其他含撲熱息痛之藥物同時服用。'),
  ('Ibuprofen', 'Nurofen', 'HK-54321', 'Ibuprofen 200mg', '200mg', '每日 2-3 次，每次 1 粒，飽肚服用。', '此藥可能引致腸胃不適，請飽肚服用。哮喘患者及胃潰瘍患者請咨詢醫生。'),
  ('Amoxicillin', 'Amoxicillin Capsules', 'HK-12345', 'Amoxicillin trihydrate 500mg', '500mg', '每日 3 次，每次 1 粒，依照醫生指示完成整個療程。', '完成整個抗生素療程。如出現過敏反應（皮疹、呼吸困難）請立即求醫。'),
  ('Omeprazole', 'Losec', 'HK-23456', 'Omeprazole 20mg', '20mg', '每日 1 次，每次 1 粒，空腹服用（早餐前最少 30 分鐘）。', '長期服用可能增加骨折風險，請定期覆診。'),
  ('Metformin', 'Glucophage', 'HK-34567', 'Metformin HCl 500mg', '500mg', '每日 2-3 次，每次 1 粒，餐後服用。', '此藥可能引致腸胃不適，初期服用常見。如出現嚴重嘔吐或呼吸困難請立即求醫。'),
  ('Salbutamol', 'Ventolin Inhaler', 'HK-45678', 'Salbutamol sulfate 100mcg/dose', '100mcg/揿', '需要時使用，每次 1-2 揿。每日不應超過 8 揿。', '此藥可能引致心跳加速及手震。如藥效減弱請立即求醫。'),
  ('Cetirizine', 'Zyrtec', 'HK-56789', 'Cetirizine HCl 10mg', '10mg', '每日 1 次，每次 1 粒，需要時服用。', '此藥引致昏睡，服藥後避免駕駛或操作機械。');
